Update push_to_elastic.yml
updated to windows powershell command

diff --git a/.github/workflows/push_to_elastic.yml b/.github/workflows/push_to_elastic.yml
--- a/.github/workflows/push_to_elastic.yml
+++ b/.github/workflows/push_to_elastic.yml
@@ -48,25 +48,31 @@ jobs:
         
     - name: Import Rules to Kibana
       run: |
-        FLAGS=""
-        if [[ "${{ github.event_name }}" == "push"  "${{ inputs.overwrite }}" == "true" ]]; then
-          FLAGS="$FLAGS --overwrite"
-        fi
-        if [[ "${{ github.event_name }}" == "push"  "${{ inputs.overwrite_exceptions }}" == "true" ]]; then
-          FLAGS="$FLAGS --overwrite-exceptions"
-        fi
-        if [[ "${{ github.event_name }}" == "push"  "${{ inputs.overwrite_action_connectors }}" == "true" ]]; then
-          FLAGS="$FLAGS --overwrite-action-connectors"
-        fi
-        if [[ "${{ github.event_name }}" == "push" ]]; then
-          SPACE="Default"  # Default to production for push events
-        else
-          echo "::error::Invalid space provided."
-          
-        fi
-        SPACE_FLAG="--space $SPACE"
-        echo $SPACE_FLAG
-        echo $FLAGS
+        $FLAGS = ""
+
+        if ($env:GITHUB_EVENT_NAME -eq "push" -and ${{ inputs.overwrite }} -eq "true") {
+        $FLAGS += " --overwrite"  
+        }
+
+        if ($env:GITHUB_EVENT_NAME -eq "push" -and ${{ inputs.overwrite_exceptions }} -eq "true") {
+        $FLAGS += " --overwrite-exceptions"
+        }
+
+        if ($env:GITHUB_EVENT_NAME -eq "push" -and ${{ inputs.overwrite_action_connectors }} -eq "true") {
+        $FLAGS += " --overwrite-action-connectors"
+        }
+
+        if ($env:GITHUB_EVENT_NAME -eq "push") {
+        $SPACE = "Default"  # Default to production for push events
+        } else {
+        Write-Error "Invalid space provided."
+        exit 1
+        }
+
+        $SPACE_FLAG = "--space $SPACE"
+
+        Write-Output $SPACE_FLAG
+        Write-Output $FLAGS
         python -m detection_rules kibana $SPACE_FLAG import-rules $FLAGS
       env:
         DR_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
