Update push_to_elastic.yml

diff --git a/.github/workflows/push_to_elastic.yml b/.github/workflows/push_to_elastic.yml
--- a/.github/workflows/push_to_elastic.yml
+++ b/.github/workflows/push_to_elastic.yml
@@ -1,39 +1,22 @@
-name: Push Latest Rules to Elastic Security Space
+name: Push to Production Sync
 
 on:
   push:
     branches:
-      - DAC-feature
+      - main
     paths:
-      - '**/*.toml'
+      - 'version.lock.json'
   workflow_dispatch:
-    inputs:
-      overwrite:
-        description: 'Overwrite existing rules'
-        required: false
-        default: 'true'
-      overwrite_exceptions:
-        description: 'Overwrite existing exceptions'
-        required: false
-        default: 'true'
-      overwrite_action_connectors:
-        description: 'Overwrite existing action connectors'
-        required: false
-        default: 'true'
-      space:
-        description: 'Kibana space to use (dev or prod)'
-        required: false
-        default: 'Default'
 
 jobs:
-  sync-to-elastic:
+  sync-to-production:
     runs-on: self-hosted
     env:
       CUSTOM_RULES_DIR: ${{ secrets.CUSTOM_RULES_DIR }}
 
     steps:
     - name: Checkout Repository
-      uses: actions/checkout@v4
+      uses: actions/checkout@v2
 
     - name: Set up Python 3.12
       uses: actions/setup-python@v2
@@ -45,27 +28,32 @@ jobs:
         python -m pip install --upgrade pip
         pip cache purge
         pip install .[dev]
-    - name: Import Rules to Kibana
+        pip install lib/kql lib/kibana
+
+    - name: Export Rules from Kibana
+      run: python -m detection_rules kibana export-rules
+      env:
+        KIBANA_URL: ${{ secrets.KIBANA_URL }}
+        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME }}
+        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
+
+    - name: Import Rules to Local Repo
+      run: python -m detection_rules import-rules-to-repo --directory ${{ env.CUSTOM_RULES_DIR }}
+
+    - name: Verify Version Lock Consistency
       run: |
-        $FLAGS = ""
-        if ($env:{{ github.event_name }} -eq "push" -or $env:{{ inputs.overwrite }} -eq "true") {
-          $FLAGS += "--overwrite"
-        }
-        if ($env:{{ github.event_name }} -eq "push" -or $env:{{ inputs.overwrite_exceptions }} -eq "true") {
-          $FLAGS += "--overwrite-exceptions"
-        }
-        if ($env:{{ github.event_name }} -eq "push" -or $env:{{ inputs.overwrite_action_connectors }} -eq "true") {
-          $FLAGS += "--overwrite-action-connectors"
-        }
-        if ($env:{{ github.event_name }} -eq "push") {
-          $SPACE = "Default"  # Default to production for push events
-        } else {
-          Write-Error "Invalid space provided. Defaulting to 'dev'."
-          $SPACE = "Default"
-        }
-        $SPACE_FLAG = "--space $SPACE"
-        python -m detection_rules kibana $SPACE_FLAG import-rules $FLAGS
-        env:
-        DR_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
-        DR_KIBANA_USER: ${{ secrets.ELASTIC_USERNAME }}
-        DR_KIBANA_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
+        if git diff --exit-code version.lock.json; then
+          echo "Version lock is consistent. Proceeding with the synchronization."
+        else
+          echo "Version lock inconsistency detected. Aborting the synchronization. Please kick off the manual sync workflow, review, and resolve."
+          exit 1
+
+    - name: Export Rules from Repo to NDJSON
+      run: python -m detection_rules export-rules-from-repo --outfile ${{ env.CUSTOM_RULES_DIR }}/rules_export.ndjson
+
+    - name: Import Rules to Kibana from NDJSON
+      run: python -m detection_rules kibana import-rules ${{ env.CUSTOM_RULES_DIR }}/rules_export.ndjson --overwrite --overwrite-exceptions --overwrite-action-connectors
+      env:
+        KIBANA_URL: ${{ secrets.KIBANA_URL }}
+        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME }}
+        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
