Update push_to_elastic.yml

diff --git a/.github/workflows/push_to_elastic.yml b/.github/workflows/push_to_elastic.yml
--- a/.github/workflows/push_to_elastic.yml
+++ b/.github/workflows/push_to_elastic.yml
@@ -1,12 +1,30 @@
-name: Push to Production Sync
+name: Push Latest Rules to Production
 
 on:
   push:
     branches:
       - main
     paths:
+      - '**/*.toml'
       - 'version.lock.json'
   workflow_dispatch:
+    inputs:
+      overwrite:
+        description: 'Overwrite existing rules'
+        required: false
+        default: 'true'
+      overwrite_exceptions:
+        description: 'Overwrite existing exceptions'
+        required: false
+        default: 'true'
+      overwrite_action_connectors:
+        description: 'Overwrite existing action connectors'
+        required: false
+        default: 'true'
+      space:
+        description: 'Kibana space to use (dev or prod)'
+        required: false
+        default: 'prod'
 
 jobs:
   sync-to-production:
@@ -16,7 +34,7 @@ jobs:
 
     steps:
     - name: Checkout Repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
 
     - name: Set up Python 3.12
       uses: actions/setup-python@v2
@@ -30,6 +48,14 @@ jobs:
         pip install .[dev]
         pip install lib/kql lib/kibana
 
+    - name: Verify Version Lock Consistency
+      run: |
+        if git diff --exit-code version.lock.json; then
+          echo "Version lock is consistent. Proceeding with the synchronization."
+        else
+          echo "Version lock inconsistency detected. Aborting the synchronization. Please kick off the manual sync workflow, review, and resolve."
+          exit 1
+
     - name: Export Rules from Kibana
       run: python -m detection_rules kibana export-rules
       env:
@@ -40,20 +66,25 @@ jobs:
     - name: Import Rules to Local Repo
       run: python -m detection_rules import-rules-to-repo --directory ${{ env.CUSTOM_RULES_DIR }}
 
-    - name: Verify Version Lock Consistency
-      run: |
-        if git diff --exit-code version.lock.json; then
-          echo "Version lock is consistent. Proceeding with the synchronization."
-        else
-          echo "Version lock inconsistency detected. Aborting the synchronization. Please kick off the manual sync workflow, review, and resolve."
-          exit 1
-
     - name: Export Rules from Repo to NDJSON
       run: python -m detection_rules export-rules-from-repo --outfile ${{ env.CUSTOM_RULES_DIR }}/rules_export.ndjson
 
     - name: Import Rules to Kibana from NDJSON
-      run: python -m detection_rules kibana import-rules ${{ env.CUSTOM_RULES_DIR }}/rules_export.ndjson --overwrite --overwrite-exceptions --overwrite-action-connectors
+      run: |
+        FLAGS=""
+        if [[ "${{ github.event_name }}" == "push" || "${{ inputs.overwrite }}" == "true" ]]; then
+          FLAGS="$FLAGS --overwrite"
+        fi
+        if [[ "${{ github.event_name }}" == "push" || "${{ inputs.overwrite_exceptions }}" == "true" ]]; then
+          FLAGS="$FLAGS --overwrite-exceptions"
+        fi
+        if [[ "${{ github.event_name }}" == "push" || "${{ inputs.overwrite_action_connectors }}" == "true" ]]; then
+          FLAGS="$FLAGS --overwrite-action-connectors"
+        fi
+        SPACE="${{ inputs.space }}"
+        SPACE_FLAG="--space $SPACE"
+        python -m detection_rules kibana $SPACE_FLAG import-rules $FLAGS ${{ env.CUSTOM_RULES_DIR }}/rules_export.ndjson
       env:
-        KIBANA_URL: ${{ secrets.KIBANA_URL }}
-        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME }}
-        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
+        DR_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
+        DR_KIBANA_USER: ${{ secrets.ELASTIC_USERNAME }}
+        DR_KIBANA_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
